name: Create Branch
run-name: Create Branch
on:
  create:
    branches:
      - 'feature/*'

jobs:
  create_branch:
    runs-on: ubuntu-latest
    
    # env:
    #   # Nombre de la nueva rama
    #   NOMBRE_DE_LA_RAMA: "${{ github.event.ref }}"
    #   NOMBRE_REPOSITORIO: $(basename "${{ github.repository }}")
    #   GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
    
    steps:
    
    - name: Detectar Creaci贸n de Rama
      run: |
        echo "La rama creada comienza con el texto clone_"
        exit 1
      if: ${{ startsWith(github.event.ref, 'clone_') }}
      
      # run: |
      #   branch_name="${{ github.event.ref }}"
        
      #   if [[ "${branch_name}" =~ ^clone_ ]]; then
      #     echo "La rama ${branch_name} comienza con 'clone_'."
      #   else
      #     echo "La rama ${branch_name} no comienza con 'clone_'."
      #   fi
    
    - name: Checkout del c贸digo
      uses: actions/checkout@v4.1.1
      if: success()
    
    # - name: listar
    #   run: |
    #     ls -la
    #     git branch
    #   # run: |
    #   #   # Clonar el repositorio    
    #   #   git clone -b ${{ env.NOMBRE_DE_LA_RAMA}} https://github.com/${{ github.repository }}.git
    #   #   cd ${{ env.NOMBRE_REPOSITORIO }}   
    # - name: Validacion de ramas
    #   run: |
    #     echo "La condici贸n no se cumpli贸. Generando un fallo."
    #     exit 1
    #   if: ${{ github.ref != 'refs/heads/master' }} && ${{ github.ref != 'refs/heads/develop' }} && ${{ github.ref != 'refs/heads/release' }}
      
    # - name: Obtener nombre de la rama
    #   run: |
    #     echo "Nombre de la Rama: ${{ env.NOMBRE_DE_LA_RAMA }}"
    #   if: success()

    # - name: Crear Rama
    #   run: |
    #     # Clonar el repositorio    
    #     git clone -b ${{ env.NOMBRE_DE_LA_RAMA}} https://github.com/${{ github.repository }}.git
    #     cd ${{ env.NOMBRE_REPOSITORIO }}
        
    # - name: Crear la nueva rama
    #   run: |
    #     # Crear la nueva rama
    #     cd ${{ env.NOMBRE_REPOSITORIO }}
        
    #     # NUEVA_RAMA="${{ env.NOMBRE_DE_LA_RAMA }}_base"
    #     # echo "Nombre de la Rama: $NUEVA_RAMA"

    #     # Checkout a nueva rama
    #     git checkout -b "${{ env.NOMBRE_DE_LA_RAMA }}_base"

    # - name: Subir nueva rama
    #   run: |
    #     # Empujar la nueva rama al repositorio
    #     cd ${{ env.NOMBRE_REPOSITORIO }}
        
    #     git config --global user.name "JoseMen97"
    #     git config --global user.email "jlms0197@gmail.com"
        
    #     git push https://${{ env.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
