name: Flujo al Crear Rama
run-name: Create Branch
on:
  create:
    branches:
      - '*'

jobs:
  create_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Obtener nombre de la rama
      run: echo "Nombre de la Rama ${{ github.event.ref }}"
