name: Create Branch
run-name: Create Branch
on:
  create:
    branches:
      - '*'

jobs:
  create_branch:
    runs-on: ubuntu-latest

    # steps:
    # - name: Obtener información de la rama
    #   run: |
    #     # Obtener el nombre de la rama creada
    #     NOMBRE_DE_LA_RAMA_CREADA="${{ github.ref }}"
    #     echo "Nombre de la Rama Creada: $NOMBRE_DE_LA_RAMA_CREADA"

    #     # Obtener la rama desde la que se creó
    #     RUTA_ORIGEN=$(echo "${{ github.event.ref }}" | cut -d'/' -f3)
    #     echo "Rama Origen: $RUTA_ORIGEN"

    # -------------------------------------------
    
    env:
      # Nombre de la nueva rama
      NOMBRE_DE_LA_RAMA: "${{ github.event.ref }}"
      NOMBRE_REPOSITORIO: $(basename "${{ github.repository }}")
      GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      
    steps:
    - name: Obtener nombre de la rama
      run: |
        echo "Nombre de la Rama: ${{ env.NOMBRE_DE_LA_RAMA }}"

    - name: Crear Rama
      run: |
        # Clonar el repositorio    
        git clone -b ${{ env.NOMBRE_DE_LA_RAMA}} https://github.com/${{ github.repository }}.git
        cd ${{ env.NOMBRE_REPOSITORIO }}
        
    - name: Crear la nueva rama
      run: |
        # Crear la nueva rama
        cd ${{ env.NOMBRE_REPOSITORIO }}
        
        # NUEVA_RAMA="${{ env.NOMBRE_DE_LA_RAMA }}_base"
        # echo "Nombre de la Rama: $NUEVA_RAMA"

        # Checkout a nueva rama
        git checkout -b "${{ env.NOMBRE_DE_LA_RAMA }}_base"

    - name: Subir nueva rama
      run: |
        # Empujar la nueva rama al repositorio
        cd ${{ env.NOMBRE_REPOSITORIO }}
        ls -la
        git branch
        git config --list
        NUEVA_RAMA="${{ env.NOMBRE_DE_LA_RAMA }}_base"
        echo "Nombre de la Rama: $NUEVA_RAMA"
        
        git push origin $NUEVA_RAMA -u ${{ env.GITHUB_TOKEN }}
