name: Create Branch
run-name: Create Branch
on:
  create:
    branches:
      - 'feature/*'

jobs:
  create_branch:
    runs-on: ubuntu-latest
    
    env:
      # Nombre de la nueva rama
      NOMBRE_DE_LA_RAMA: "${{ github.event.ref }}"
      NOMBRE_REPOSITORIO: "${{ github.event.repository.name }}"
      GITHUB_TOKEN: "${{ secrets.TOKEN_GITHUB }}"
    
    steps:
    
    - name: Detectar Creación de Rama
      run: |
        echo "La rama creada comienza con el texto clone_"
        exit 1
      if: ${{ startsWith(github.event.ref, 'clone_') }}
    
    - name: Checkout del código
      uses: actions/checkout@v4.1.1
      if: success()

    - name: Crear la nueva rama
      run: |
        git checkout -b "clone_${{ env.NOMBRE_DE_LA_RAMA }}"
      if: success()

    - name: Push de la nueva rama
      run: |
        ls -la
        
        git config --global user.name "JoseMen97"
        git config --global user.email "jlms0197@gmail.com"
        git config --list
        
        # git push origin "clone_${{ env.NOMBRE_DE_LA_RAMA }}" -u ${{ env.GITHUB_TOKEN }}
        # git push https://${{ env.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      if: success()
