name: pull_request
run-name: Deteccion pull request
on:
  pull_request

jobs:
  detect_pullrequest:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repositorio
        uses: actions/checkout@v4.1.1
        
      - name: Validar cambios
        run: |
          echo "origin/${{ github.event.pull_request.base.ref }}"
          echo "${{ github.event.pull_request.head.ref }}"

          git checkout ${{ github.event.pull_request.base.ref }}
          git checkout ${{ github.event.pull_request.head.ref }}
          
          git diff ${{ github.event.pull_request.head.ref }} ${{ github.event.pull_request.base.ref }}
