name: pull_request
run-name: Deteccion pull request
on:
  pull_request
  
permissions: write

jobs:
  detect_pullrequest:
    runs-on: ubuntu-latest
      
    steps:
      - name: checkout repositorio
        run: |
          git clone ${{ github.event.pull_request.base.repo.clone_url }}
          cd ${{ github.event.pull_request.base.repo.name }}
          git checkout ${{ github.event.pull_request.head.ref }}

      - name: Validar cambios
        id: valid_changes
        run: |
          python -m pip install pyyaml
          
          cd ${{ github.event.pull_request.base.repo.name }}
          git diff "origin/${{ github.event.pull_request.base.ref }}" "origin/${{ github.event.pull_request.head.ref }}" --name-only >> output.txt

          python .github/script/rwFileYaml.py ${{ github.sha }} ${{ github.actor }}
          
          mv *_changeset_new.yaml changesets
          
      - name: liquibase validate
        uses: liquibase-github-actions/validate@v4.25.1
        with:
          changelogFile: "${{ github.event.pull_request.base.repo.name }}/changelog.yaml"
          url: "jdbc:oracle:thin:@2.tcp.ngrok.io:17603/admindb"
          username: "FO"
          password: ${{secrets.password}}

      # - name: Liquibase Status Action
      #   uses: liquibase-github-actions/status@v4.25.1
      #   with:
      #     changelogFile: "changelog.yaml"
      #     url: "jdbc:oracle:thin:@2.tcp.ngrok.io:18988/admindb"
      #     username: "FO"
      #     password: ${{secrets.password}}

      # - name: Liquibase Update Sql Action
      #   uses: liquibase-github-actions/update-sql@v4.25.1
      #   with:
      #     changelogFile: "changelog.yaml"
      #     url: "jdbc:oracle:thin:@2.tcp.ngrok.io:18988/admindb"
      #     username: "FO"
      #     password: ${{secrets.password}}
      # - name: Liquibase Update Action
      #   uses: liquibase-github-actions/update@v4.25.1
      #   with:
      #     changelogFile: "changelog.yaml"
      #     url: "jdbc:oracle:thin:@2.tcp.ngrok.io:18988/admindb"
      #     username: "FO"
      #     password: ${{secrets.password}}
