name: pull_request
run-name: Deteccion pull request
on:
  pull_request

jobs:
  detect_pullrequest:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repositorio
        run: |
          git clone ${{ github.event.pull_request.base.repo.clone_url }}
        
      - name: Validar cambios
        run: |
          cd ${{ github.event.pull_request.base.repo.name }}
          
          echo "origin/${{ github.event.pull_request.base.ref }}"
          echo "${{ github.event.pull_request.head.ref }}"

          git checkout ${{ github.event.pull_request.base.ref }}
          git checkout ${{ github.event.pull_request.head.ref }}

          git branch
          
          git diff ${{ github.event.pull_request.head.ref }} ${{ github.event.pull_request.base.ref }}
