name: pull_request
run-name: Deteccion pull request
on:
  pull_request

jobs:
  detect_pullrequest:
    runs-on: ubuntu-latest
    
    steps:
      - name: Validar cambios
        run: |
          git diff ${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.ref }}
