name: pull_request
run-name: Deteccion pull request
on:
  pull_request:
    types: [opened]

jobs:
  detect_pullrequest:
    runs-on: ubuntu-latest
    
    steps:
      - name: view event
        run: echo "${{ toJson(github) }}"
