name: pull_request
run-name: Deteccion pull request
on:
  pull_request

jobs:
  detect_pullrequest:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repositorio
        run: git clone ${{ github.event.pull_request.base.repo.clone_url }}
        
      - name: Validar cambios
        id: valid_changes
        run: |
          cd ${{ github.event.pull_request.base.repo.name }}
          echo "diff_output=$(git diff "origin/${{ github.event.pull_request.base.ref }}" "origin/${{ github.event.pull_request.head.ref }}" --name-only)" >> $GITHUB_OUTPUT
          
      - name: list step
        run: |
          archivos="${{ steps.valid_changes.outputs.diff_output }}"
          echo $archivos
