name: pull_request
run-name: Deteccion pull request
on:
  pull_request

jobs:
  detect_pullrequest:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repositorio
        run: |
          git clone ${{ github.event.pull_request.base.repo.clone_url }}
        
      - name: Validar cambios
        run: |
          cd ${{ github.event.pull_request.base.repo.name }}
          echo "diff_output=$(git diff "origin/${{ github.event.pull_request.base.ref }}" "origin/${{ github.event.pull_request.head.ref }}" --name-only)" >> $GITHUB_OUTPUT
          
          echo "$diff_output"
